---
title: "Confidence interval interpretation"
author: "Giuseppe Tinti Tomio"
output:
    xaringan::moon_reader:
        self_contained: yes
        nature:
            highlightStyle: github
            highlightLines: true
            countIncrementalSlides: false
---

```{css css setup, echo = FALSE}
orange {
  color: #E69F00;
}

green {
    color: #009E73;
}

blue {
    color: #0072B2;
}
```

```{r R setup, include = FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    fig.align = "center",
    fig.height = 7,
    fig.width = 10,
    out.height = "100%"
)

library(tidyverse)
library(xkcd)

POPULATION_SIZE <- 20
TRUE_LOCATION <- 170
TRUE_SCALE <- 10

SEED <- 42

RED <- scales::hue_pal()(2)[1]
BLUE <- scales::hue_pal()(2)[2]
BASE_SIZE <- 22

generate_stickmen_data <- function(
    column_count,
    row_count,
    height_location,
    height_scale
) {
    total_count <- column_count * row_count

    x <- rep(seq(0, column_count - 1), times = row_count)
    y <- - 3.5 * rep(seq(0, row_count - 1), each = column_count)
    draw_height <- 1
    xy_ratio <- diff(range(x)) / diff(range(y))

    down <- - pi / 2
    tilt <- pi / 12
    left_tilted <- down + tilt
    right_tilted <- down - tilt

    is_selected <- FALSE
    height <- exact_rnorm(total_count, height_location, height_scale)

    data <- tibble(
        x = x,
        y = y,
        draw_height = draw_height,
        xy_ratio = xy_ratio,
        spine_angle = down,
        lefth_humerus_angle = left_tilted,
        right_humerus_angle = right_tilted,
        left_radius_angle = left_tilted,
        right_radius_angle = right_tilted,
        left_leg_angle = left_tilted,
        right_leg_angle = right_tilted,
        neck_angle = down,
        is_selected = is_selected,
        height = height
    )

    return(data)
}

exact_rnorm <- function(
    count,
    location,
    scale
) {
    sample <- rnorm(count)
    sample <- as.vector(scale(sample))
    sample <- sample * scale + location

    return(sample)
}

plot_stickmen <- function(
    data
) {
    plot <-
        ggplot() +
        xkcdman(aes(
            x = x,
            y = y,
            scale = draw_height,
            ratioxy = xy_ratio,
            angleofspine = spine_angle,
            anglelefthumerus = lefth_humerus_angle,
            anglerighthumerus = right_humerus_angle,
            angleleftradius = left_radius_angle,
            anglerightradius = right_radius_angle,
            angleleftleg = left_leg_angle,
            anglerightleg = right_leg_angle,
            angleofneck = neck_angle,
            color = is_selected
        ), data) +
        scale_color_manual(values = c(`TRUE` = RED, `FALSE` = BLUE), guide = "none") +
        theme_void()

    return(plot)
}

base_theme <- function(

) {
    return(theme_minimal(BASE_SIZE))
}

set.seed(SEED)
```

```{r reference setup, include = FALSE, cache = FALSE}
library(RefManageR)

BibOptions(
    bib.style = "authoryear",
    max.names = 1,
    cite.style = "authoryear",
    style = "markdown",
    hyperlink = FALSE
)

bibliography <- ReadBib("./bibliography.bib")
```

```{r processing, include = FALSE}
stickmen_data <- generate_stickmen_data(5, 3, TRUE_LOCATION, TRUE_SCALE)
```

```{r plot}
plot_stickmen(stickmen_data)
```
